### ISSUE TITLE
Cannot import .zip file into JATOS

### ISSUE THREAD

**Issue by deforster** [ejpedersen/grat_rep1#4]
Can someone try to zip the jatos structure and import it? I get a 'Study is invalid' error. I only changed the consent formatting, so there shouldn't be any issue. I'm going to skim the message boards for support, as well, but I thought one of you could give it a shot. @jairo-ramos @lmwadsworth @ejpedersen

**Comment by lmwadsworth** [comment]
I just did! It says it can’t show files that are this big right now though.. check it out and let me know if there’s a problem!

**Comment by deforster** [comment]
This is totally bonkers. The zip folder you created imported perfectly. I then created a zip folder again and I got a 'study is invalid' error... I think you both use Macs so I'm going to test this on my Mac when I get home to see if it's an issue with the Windows compression. Thanks for the help!

**Comment by deforster** [comment]
@lmwadsworth Sorry, I just noticed that the .zip folder you uploaded was an older version. Would you mind zipping the grat_rep1_jatos from the repo? I did notice that I *still* had an issue when I took your (working) gratitude.zip folder, extracted, then re-compressed, so something definitely isn't working right on my end.

**Comment by lmwadsworth** [comment]
try now!

**Comment by deforster** [comment]
So close! Instead of compressing the master structure, I just need the grat_rep1_jatos folder to be compressed. Sorry for the ambiguous direction (and thanks a ton for getting back to me so promptly).

**Comment by lmwadsworth** [comment]
Oh I see! Sorry! I don’t have that version on my computer- Jairo, can you please send that to Danny!

**Comment by deforster** [comment]
Jairo solved this via email. The folder structure has to be recreated within the JATOS GUI and then exported as a .zip. It cannot merely read any .zip with the same folder structure, so there must be some metadata added to the .zip folder when exported from JATOS.
